version: '3.9'
services:
  postgres:
    image: postgres:13-alpine
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
    expose:
      - "5432"
    ports:
      - "5436:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data/
  redis:
    image: redis:6
    expose:
      - "6379"
    ports:
      - "6379:6379"
    restart: always
  jaeger:
    image: jaegertracing/all-in-one:1.27
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    expose:
      - "16686"
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    restart: always
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    environment: {}
    expose:
      - "4317"
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    volumes:
      - "${PWD}/api/hack/observability:/observability"
    command: ["--config=/observability/otel-config.yaml", "${OTELCOL_ARGS}"]
    restart: always
    depends_on:
      - jaeger
  grafana:
    image: grafana/grafana:7.1.5
    ports:
      - 3000:3000
    volumes:
      - ./api/hack/observability/grafana/provisioning:/etc/grafana/provisioning
#      - ./api/hack/observability/grafana/dashboards:/etc/grafana/demo-dashboards
      - grafana_data:/var/lib/grafana
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./api/hack/observability/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
  asynqmon:
    image: hibiken/asynqmon
    command: ["--redis-addr=redis:6379"]
    ports:
      - 8011:8080

volumes:
  postgres:
  grafana_data:
  prometheus_data: