version: '3.9'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
    expose:
      - "5432"
    ports:
      - "5436:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data/

volumes:
  postgres: