apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: booking-service
  name: booking-service
  namespace: booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - image: imrenagi/booking:v1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9999
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9999
            initialDelaySeconds: 5
            periodSeconds: 5
          args:
            - ./booking
            - server
            - --port=9999
          name: booking
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: DB_HOST
              value: "10.35.113.3"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: booking-db-secret
                  key: username
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: booking-db-secret
                  key: name
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: booking-db-secret
                  key: userpassword
            - name: ENVIRONMENT
              value: development
            - name: TESTYA
              value: testya
            - name: OTEL_RECEIVER_OTLP_ENDPOINT
              value: "otel-collector.booking:4317"
            - name: ASYNQ_REDIS_HOST
              value: "redis-master.redis:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: booking
  labels:
    app: booking-service
spec:
  ports:
    - name: http
      port: 9999
      protocol: TCP
      targetPort: 9999
  selector:
    app: booking-service
  type: ClusterIP