apiVersion: batch/v1
kind: CronJob
metadata:
  name: load-generator
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hey
              image: williamyeh/hey
              args:
                - "-z"
                - "5m"
                - "-c"
                - "3"
                - "-q"
                - "2"
                - "-m"
                - "POST"
                - "-d"
                - '{"show_id": "b9b0d5da-98a4-4b09-b5f5-83dc0c3b9964"}'
                - "http://booking-service.booking:9999/api/v2/booking"
          restartPolicy: Never
