apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: otel-collector
  namespace: booking
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
  endpoints:
    - port: 8889
      interval: 5s