receivers:
  otlp:
    protocols:
      grpc:

exporters:
  googlecloud:
    project: io-extended-2022
    retry_on_failure:
      enabled: false
#    metric:
#      create_metric_descriptor_buffer_size: 20
#    log:
#      default_log_name: opentelemetry.io/collector-exported-log

  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels: { }

  logging:

  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

  otlp:
    endpoint: ${OTEL_NEW_RELIC_EXPORTER_OTLP_ENDPOINT}
    headers:
      api-key: ${OTEL_NEW_RELIC_EXPORTER_API_KEY}

processors:
  batch:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 65
    spike_limit_percentage: 60
  resourcedetection:
    detectors: [gcp]
    timeout: 10s

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [ pprof, zpages, health_check ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors:
        - memory_limiter
        - batch
      exporters:
#        - logging
        - jaeger
        - googlecloud
#        - otlp
    metrics:
      receivers: [ otlp ]
      processors:
        - memory_limiter
        - batch
      exporters:
#        - logging
        - prometheus
        - googlecloud
#        - otlp
